### ISSUE TITLE
Not working in 5.1.0

### ISSUE THREAD

**Issue by ezequias** [congamble/franz-recipe-evernote#2]
I was trying to make it work in my Franz in 5.1.0 version but it does not work.

![evernote0](https://user-images.githubusercontent.com/539561/60596693-e6cb4780-9d7f-11e9-90d8-b7c3c780b6af.JPG)
![evernote](https://user-images.githubusercontent.com/539561/60596699-ea5ece80-9d7f-11e9-99fb-6bf027facda9.JPG)

Could someone tell me how to make it work please?

Thanks in advance.

Ezequias.

**Comment by congamble** [comment]
Ensure you've updated to the latest Franz.

Once all instructions are followed in the readme, head to 'Add new service', then to the 'Development' category. You'll see it there. 

Retested in 5.2.0 and fully functional.
